---
# setup_sssd_as_client_for_389_server/tasks/main.yml

#
# include files per topic
#

- ansible.builtin.include_tasks: openldap.yml
  args:
    apply:
      tags:
        - 'openldap'
  tags:
    - 'openldap'

- ansible.builtin.include_tasks: sssd.yml
  args:
    apply:
      tags:
        - 'sssd'
  tags:
    - 'sssd'

- ansible.builtin.include_tasks: nsswitch.yml
  args:
    apply:
      tags:
        - 'nsswitch'
  tags:
    - 'nsswitch'

- ansible.builtin.include_tasks: sshd.yml
  args:
    apply:
      tags:
        - 'sshd'
  tags:
    - 'sshd'

- ansible.builtin.include_tasks: 'pam_configuration_SUSE.yml'
  args:
    apply:
      tags:
        - 'pam_on_suse'
  when: 'ansible_os_family == "Suse"'
  tags:
    - 'pam_on_suse'
