---
# setup_sssd_as_client_for_389_server/tasks/main.yml

#
# /etc/openldap/ldap.conf
#
- name: 'Create /etc/openldap/ldap.conf'
  template:
    src: 'etc_openldap_ldap.conf.j2'
    dest: '/etc/openldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

#
# create directory /etc/openldap/certs/
#
- name: 'Create directory /etc/openldap/certs/ on all ldapclients'
  file:
    dest: '/etc/openldap/certs/'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

#
# include files per topic
#

- include_tasks: sssd.yml
  args:
    apply:
      tags:
        - 'sssd'
  tags:
    - 'sssd'

- include_tasks: nsswitch.yml
  args:
    apply:
      tags:
        - 'nsswitch'
  tags:
    - 'nsswitch'

- include_tasks: sshd.yml
  args:
    apply:
      tags:
        - 'sshd'
  tags:
    - 'sshd'

- include_tasks: 'pam_configuration_SUSE.yml'
  args:
    apply:
      tags:
        - 'pam_on_suse'
  when: 'ansible_os_family == "Suse"'
  tags:
    - 'pam_on_suse'
