---
# setup_sssd_as_client_for_389_server/tasks/main.yml

#
# /etc/openldap/ldap.conf
#
- name: 'Create /etc/openldap/ldap.conf'
  template:
    src: 'etc_openldap_ldap.conf.j2'
    dest: '/etc/openldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- include_tasks: sssd.yml

- include_tasks: nsswitch.yml

#
# sshd configuration
#
- name: 'Prepare the sshd configuration'
  block:

  - name: 'sshd_config: Make sure password authentication is enabled'
    lineinfile:
      path: '/etc/ssh/sshd_config'
      line: 'PasswordAuthentication yes'
      regexp: '^PasswordAuthentication'
      insertafter: '^#PasswordAuthentication'
      state: 'present'
    notify:
      - 'Restart the sshd service'

  - name: 'sshd_config: Make sure pubkey authentication is enabled'
    lineinfile:
      path: '/etc/ssh/sshd_config'
      line: 'PubkeyAuthentication yes'
      regexp: '^PubkeyAuthentication'
      insertafter: '^#PubkeyAuthentication'
      state: 'present'
    notify:
      - 'Restart the sshd service'

  - name: 'sshd_config: Make sure AuthorizedKeysCommand (needed for pubkey authentication) is enabled'
    lineinfile:
      path: '/etc/ssh/sshd_config'
      line: 'AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'
      regexp: '^AuthorizedKeysCommand\ .*$'
      insertafter: '^#AuthorizedKeysCommand none'
      state: 'present'
    notify:
      - 'Restart the sshd service'

  - name: 'sshd_config: Make sure AuthorizedKeysCommandUser (needed for pubkey authentication) is enabled'
    lineinfile:
      path: '/etc/ssh/sshd_config'
      line: 'AuthorizedKeysCommandUser nobody'
      regexp: '^AuthorizedKeysCommandUser'
      insertafter: '^#AuthorizedKeysCommandUser'
      state: 'present'
    notify:
      - 'Restart the sshd service'

- include_tasks: 'pam_configuration_SUSE.yml'
  args:
    apply:
      tags:
        - 'pam_on_suse'
  when: 'ansible_os_family == "Suse"'
  tags:
    - 'pam_on_suse'
