---
# setup_sssd_as_client_for_389_server/tasks/main.yml

- name: 'Create /etc/openldap/ldap.conf'
  template:
    src: 'etc_openldap_ldap.conf.j2'
    dest: '/etc/openldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Stop and disable the nscd service'
  service:
    name: 'nscd'
    state: 'stopped'
    enabled: 'false'
  when: 'ansible_os_family == "SUSE"'

- name: 'Create /etc/openldap/ldap.conf'
  template:
    src: 'sssd.conf_only_server_admins_group_allowed.j2'
    dest: '/etc/sssd/sssd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
