---
# setup_sssd_as_client_for_389_server/tasks/main.yml

#
# /etc/openldap/ldap.conf
#
- name: 'Create /etc/openldap/ldap.conf'
  template:
    src: 'etc_openldap_ldap.conf.j2'
    dest: '/etc/openldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- include_tasks: sssd.yml

- include_tasks: nsswitch.yml

- include_tasks: sshd.yml

- include_tasks: 'pam_configuration_SUSE.yml'
  args:
    apply:
      tags:
        - 'pam_on_suse'
  when: 'ansible_os_family == "Suse"'
  tags:
    - 'pam_on_suse'
