---
# setup_sssd_as_client_for_389_server/tasks/nsswitch.yml

#
# nsswitch configuration
#

- name: 'Prepare nsswitch configuration'
  block:

  - name: '/etc/nsswitch.conf: make sure sss is present in passwd line'
    lineinfile:
      path: '/etc/nsswitch.conf'
      line: 'passwd: \1 sss \2'
      regexp: '^passwd:(\s\w*)?(\ssss)?(\s\w*)*'
      state: 'present'
      backrefs: 'yes'
      backup: 'yes'

  - name: '/etc/nsswitch.conf: make sure sss is present in group line'
    lineinfile:
      path: '/etc/nsswitch.conf'
      line: 'group: \1 sss \2'
      regexp: '^group:(\s\w*)?(\ssss)?(\s\w*)*'
      state: 'present'
      backrefs: 'yes'
      backup: 'yes'

  - name: '/etc/nsswitch.conf: make sure sss is present in shadow line'
    lineinfile:
      path: '/etc/nsswitch.conf'
      line: 'shadow: \1 sss \2'
      regexp: '^shadow:(\s\w*)?(\ssss)?(\s\w*)*'
      state: 'present'
      backrefs: 'yes'
      backup: 'yes'
