---
# setup_sssd_as_client_for_389_server/tasks/openldap.yml

#
# /etc/openldap/ldap.conf
#
- name: 'Create /etc/openldap/ldap.conf'
  ansible.builtin.template:
    src: 'etc_openldap_ldap.conf.j2'
    dest: '/etc/openldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

#
# create directory /etc/openldap/certs/
#
- name: 'Create directory /etc/openldap/certs/ on all ldapclients'
  ansible.builtin.file:
    dest: '/etc/openldap/certs/'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
