---
# setup_sssd_as_client_for_389_server/tasks/sshd.yml

#
# sshd configuration
#
- name: 'Make sure password authentication is enabled in sshd_config'
  ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    line: 'PasswordAuthentication yes'
    regexp: '^PasswordAuthentication'
    insertafter: '^#PasswordAuthentication'
    state: 'present'
  notify:
    - 'Restart the sshd service'

- name: 'Make sure pubkey authentication is enabled in sshd_config'
  ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    line: 'PubkeyAuthentication yes'
    regexp: '^PubkeyAuthentication'
    insertafter: '^#PubkeyAuthentication'
    state: 'present'
  notify:
    - 'Restart the sshd service'

- name: 'Make sure AuthorizedKeysCommand (needed for pubkey authentication) is enabled in sshd_config'
  ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    line: 'AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'
    regexp: '^AuthorizedKeysCommand\ .*$'
    insertafter: '^#AuthorizedKeysCommand none'
    state: 'present'
  notify:
    - 'Restart the sshd service'

- name: 'Make sure AuthorizedKeysCommandUser (needed for pubkey authentication) is enabled in sshd_config'
  ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    line: 'AuthorizedKeysCommandUser nobody'
    regexp: '^AuthorizedKeysCommandUser'
    insertafter: '^#AuthorizedKeysCommandUser'
    state: 'present'
  notify:
    - 'Restart the sshd service'
