---
# setup_sssd_as_client_for_389_server/tasks/sssd.yml

#
# disable the nsdcd service on SUSE/openSUSE
#
- name: 'Stop and disable the nscd service'
  ansible.builtin.service:
    name: 'nscd'
    state: 'stopped'
    enabled: 'false'
  when: 'ansible_os_family == "Suse"'

#
# /etc/sssd/sssd.conf
#
- name: 'Create /etc/sssd/sssd.conf'
  ansible.builtin.template:
    src: 'sssd.conf_only_server_admins_group_allowed.j2'
    dest: '/etc/sssd/sssd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - 'Start the sssd service'
    - 'Restart the sssd service'
